# Generated by Django 5.0.6 on 2024-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_emergencyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_approved_agency',
            name='agency_id',
            field=models.CharField(default=['Y', '3', '4', 'P', 'M', 'V', '7', '9', 'O', '3'], max_length=10, unique=True),
        ),
    ]
