# Generated by Django 5.0.6 on 2024-12-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_non_approved_agency_agency_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_approved_agency',
            name='agency_id',
        ),
    ]
