# Generated by Django 5.0.6 on 2024-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_remove_non_approved_agency_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='non_approved_agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
