# Generated by Django 5.0.6 on 2024-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_agency_slug_non_approved_agency_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='non_approved_agency',
            name='slug',
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='non_approved_agency',
            name='agency_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
