# Generated by Django 5.0.6 on 2024-12-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_remove_agency_slug_remove_non_approved_agency_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='non_approved_agency',
            name='agency_id',
        ),
    ]
