# Generated by Django 5.0.6 on 2024-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_remove_agency_agency_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
