# Generated by Django 5.0.6 on 2024-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_agency_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='locality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='non_approved_agency',
            name='address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='non_approved_agency',
            name='city',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='non_approved_agency',
            name='email',
            field=models.EmailField(max_length=10),
        ),
        migrations.AlterField(
            model_name='non_approved_agency',
            name='locality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='non_approved_agency',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='non_approved_agency',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='non_approved_agency',
            name='website',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request',
            field=models.TextField(max_length=10),
        ),
    ]
