# Generated by Django 5.0.6 on 2024-12-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_alter_agency_about_alter_agency_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='approve',
        ),
    ]
